# Initialize GitHub Backup Repository
# Usage: .\init-repo.ps1 [-RepoUrl "https://github.com/username/repo.git"] [-RepoPath "C:\Users\HPM\qwen-autoclaw-backup"]
# This creates and initializes the backup repository structure

param(
    [string]$RepoUrl,
    [string]$RepoPath
)

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

if (-not $RepoPath) {
    $RepoPath = Join-Path $env:USERPROFILE "qwen-autoclaw-backup"
}

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  INITIALIZE BACKUP REPOSITORY" -ForegroundColor Cyan
Write-Host "  Time: $timestamp" -ForegroundColor Cyan
Write-Host "  Path: $RepoPath" -ForegroundColor Yellow
Write-Host "========================================`n" -ForegroundColor Cyan

# Step 1: Create repository directory
Write-Host "[STEP 1] Creating repository directory..." -ForegroundColor Cyan

if (Test-Path $RepoPath) {
    Write-Host "[FOUND] Directory already exists" -ForegroundColor Yellow
    Write-Host "Continue with existing directory? (y/n)" -ForegroundColor Yellow
    $response = Read-Host
    
    if ($response -ne "y" -and $response -ne "Y") {
        Write-Host "Initialization cancelled" -ForegroundColor Yellow
        return
    }
} else {
    New-Item -ItemType Directory -Force -Path $RepoPath | Out-Null
    Write-Host "[OK] Directory created" -ForegroundColor Green
}

Push-Location $RepoPath

try {
    # Step 2: Initialize git if needed
    Write-Host "`n[STEP 2] Initializing git repository..." -ForegroundColor Cyan
    
    if (-not (Test-Path ".git")) {
        git init
        Write-Host "[OK] Git repository initialized" -ForegroundColor Green
    } else {
        Write-Host "[FOUND] Git repository already exists" -ForegroundColor DarkYellow
    }
    
    # Step 3: Create directory structure
    Write-Host "`n[STEP 3] Creating directory structure..." -ForegroundColor Cyan
    
    $directories = @(
        "qwen-code\knowledge-base",
        "qwen-code\skills",
        "qwen-code\projects",
        "openclaw-autoclaw\agents",
        "openclaw-autoclaw\skills",
        "openclaw-autoclaw\workspace",
        "openclaw-autoclaw\cron",
        "openclaw-autoclaw\canvas",
        "openclaw-autoclaw\devices",
        "gemini-cli",
        "scripts",
        "logs"
    )
    
    foreach ($dir in $directories) {
        $fullPath = Join-Path $RepoPath $dir
        if (-not (Test-Path $fullPath)) {
            New-Item -ItemType Directory -Force -Path $fullPath | Out-Null
            Write-Host "  Created: $dir" -ForegroundColor DarkGray
        }
    }
    
    Write-Host "[OK] Directory structure created" -ForegroundColor Green
    
    # Step 4: Create .gitignore
    Write-Host "`n[STEP 4] Creating .gitignore..." -ForegroundColor Cyan
    
    $gitignoreTemplate = Join-Path "C:\Users\HPM\.qwen\sauvegarde-system" ".gitignore-template"
    
    if (Test-Path $gitignoreTemplate) {
        Copy-Item -Path $gitignoreTemplate -Destination (Join-Path $RepoPath ".gitignore") -Force
        Write-Host "[OK] .gitignore created from template" -ForegroundColor Green
    } else {
        # Create basic .gitignore inline
@"
# Sensitive files
oauth_creds.json
*.key
*.pem
.env

# Cache and temp
*.cache
tmp/
*.log

# OS files
.DS_Store
Thumbs.db
desktop.ini

# Browser extension caches
*.crx

# Downloaded installers
*.exe
"@ | Out-File -FilePath (Join-Path $RepoPath ".gitignore") -Encoding UTF8
        Write-Host "[OK] .gitignore created (basic)" -ForegroundColor Green
    }
    
    # Step 5: Create README.md
    Write-Host "`n[STEP 5] Creating README.md..." -ForegroundColor Cyan
    
@"
# 🔄 Qwen Code & AutoClaw/OpenClaw Backup Repository

> **Auto-generated backup repository** - Last backup: $timestamp

---

## 📊 Repository Structure

- **qwen-code/** - Qwen Code configuration and files
- **openclaw-autoclaw/** - AutoClaw/OpenClaw instance backup
- **gemini-cli/** - Gemini CLI mission mandate
- **scripts/** - Backup automation scripts
- **logs/** - Backup history and logs

---

## 🚀 Quick Setup on New Machine

\`\`\`powershell
# Clone this repository
git clone REPO_URL_HERE
cd qwen-autoclaw-backup

# Run setup script
cd scripts
.\setup-new-instance.ps1

# Follow prompts
\`\`\`

See \`SETUP_GUIDE.md\` for detailed instructions.

---

## 📈 Backup Status

- **Last Backup:** $timestamp
- **Status:** ✅ Active
- **Auto-Backup:** Every 5 minutes (via scheduled task)

---

## 🔒 Security

This repository contains configuration files. Sensitive credentials should:
- Be stored in environment variables
- Use encrypted files
- Never be committed directly

Review files before pushing to public repositories.

---

*Generated by Qwen & AutoClaw Backup System*
"@ | Out-File -FilePath (Join-Path $RepoPath "README.md") -Encoding UTF8
    
    Write-Host "[OK] README.md created" -ForegroundColor Green
    
    # Step 6: Copy setup guide
    Write-Host "`n[STEP 6] Copying documentation..." -ForegroundColor Cyan
    
    $setupGuide = "C:\Users\HPM\.qwen\sauvegarde-system\SETUP_GUIDE.md"
    if (Test-Path $setupGuide) {
        Copy-Item -Path $setupGuide -Destination (Join-Path $RepoPath "SETUP_GUIDE.md") -Force
        Write-Host "[OK] SETUP_GUIDE.md copied" -ForegroundColor Green
    }
    
    # Step 7: Copy scripts
    Write-Host "`n[STEP 7] Copying backup scripts..." -ForegroundColor Cyan
    
    $scriptsSource = "C:\Users\HPM\.qwen\sauvegarde-system\scripts"
    if (Test-Path $scriptsSource) {
        Copy-Item -Path "$scriptsSource\*" -Destination (Join-Path $RepoPath "scripts") -Recurse -Force
        $scriptCount = (Get-ChildItem (Join-Path $RepoPath "scripts") -File).Count
        Write-Host "[OK] $scriptCount scripts copied" -ForegroundColor Green
    }
    
    # Step 8: Create initial log
    Write-Host "`n[STEP 8] Initializing backup log..." -ForegroundColor Cyan
    
@"
# Backup History

## $timestamp - Repository Initialized
- **Status:** SUCCESS
- **Type:** INITIALIZATION
- **Components:** 0/0 (empty repository)
- **Next:** Run first backup with backup-all.ps1

"@ | Out-File -FilePath (Join-Path $RepoPath "logs\backup-history.md") -Encoding UTF8
    
    Write-Host "[OK] Backup log created" -ForegroundColor Green
    
    # Step 9: Initial commit
    Write-Host "`n[STEP 9] Creating initial commit..." -ForegroundColor Cyan
    
    git add .
    $status = git status --porcelain
    
    if ($status) {
        git commit -m "Initialize backup repository structure - $timestamp"
        Write-Host "[OK] Initial commit created" -ForegroundColor Green
    } else {
        Write-Host "[WARN] No changes to commit" -ForegroundColor DarkYellow
    }
    
    # Step 10: Add remote if URL provided
    if ($RepoUrl) {
        Write-Host "`n[STEP 10] Adding remote repository..." -ForegroundColor Cyan
        
        $remotes = git remote
        if ($remotes -contains "origin") {
            git remote remove origin
        }
        
        git remote add origin $RepoUrl
        Write-Host "[OK] Remote added: $RepoUrl" -ForegroundColor Green
        
        Write-Host "`n[FINAL] Pushing to GitHub..." -ForegroundColor Cyan
        git push -u origin main
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "[OK] Repository pushed to GitHub" -ForegroundColor Green
        } else {
            Write-Host "[WARN] Push failed - run 'git push' manually after configuring authentication" -ForegroundColor Yellow
        }
    } else {
        Write-Host "`n[INFO] No repository URL provided" -ForegroundColor DarkYellow
        Write-Host "To add remote later:" -ForegroundColor DarkGray
        Write-Host "  git remote add origin https://github.com/username/repo.git" -ForegroundColor Gray
        Write-Host "  git push -u origin main" -ForegroundColor Gray
    }
    
    # Summary
    Write-Host "`n========================================" -ForegroundColor Cyan
    Write-Host "  INITIALIZATION COMPLETE!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "`nRepository: $RepoPath" -ForegroundColor White
    Write-Host "Structure: $(($directories).Count) directories created" -ForegroundColor White
    Write-Host "Scripts: $scriptCount automation scripts" -ForegroundColor White
    
    Write-Host "`nNext steps:" -ForegroundColor Yellow
    Write-Host "1. Run first backup: .\scripts\backup-all.ps1" -ForegroundColor White
    Write-Host "2. Configure git authentication" -ForegroundColor White
    Write-Host "3. Install auto-backup: .\scripts\watch-and-commit.ps1 -Install" -ForegroundColor White
    Write-Host "4. Test restore procedure" -ForegroundColor White
    
    Write-Host "`n========================================`n" -ForegroundColor Cyan
    
}
finally {
    Pop-Location
}
